owner: LangbaseInc
repo: status
sites:
  - name: Langbase API
    url: https://api.langbase.com/health
status-website:
  cname: status.langbase.com
  logoUrl: https://raw.githubusercontent.com/LangbaseInc/docs-images/refs/heads/main/design/logo/logo-symbol.svg
  name: Langbase Status
  navbar:
    - title: Langbase
      href: https://langbase.com
    - title: Status
      href: /
    - title: Subscribe on GitHub
      href: https://github.com/$OWNER/$REPO/issues
i18n:
  footer: ''
